"""Shared result DTOs — import from here or from .results directly."""
from .results import (
    SQLGenerationResult,
    FilterSummaryResult,
    AggregationSummaryResult,
    FilterAggregationSQLResult,
    FilterAggSummaryResult,
    CvInfoSummaryResult,
    FilterAgentResult,
    AggregationAgentResult,
    FilterAggregationResult,
    ChitChatResult,
    IntentClassificationResult,
    FlowResult,
    TitleResult,
    CvInfoExtraction,
    CvInfoResult,
    HrFeedbackExtraction,
    ComparisonExtraction,
    ComparisonDecision,
)

__all__ = [
    "SQLGenerationResult",
    "FilterSummaryResult",
    "AggregationSummaryResult",
    "FilterAggregationSQLResult",
    "FilterAggSummaryResult",
    "CvInfoSummaryResult",
    "FilterAgentResult",
    "AggregationAgentResult",
    "FilterAggregationResult",
    "ChitChatResult",
    "IntentClassificationResult",
    "FlowResult",
    "TitleResult",
    "CvInfoExtraction",
    "CvInfoResult",
    "HrFeedbackExtraction",
    "ComparisonExtraction",
    "ComparisonDecision",
]
